### ISSUE TITLE
NPE in ICC_Profile.intFromBigEndian

### ISSUE THREAD

**Issue by SoltauFintel** [red6/pdfcompare#82]
Do you know what cause this exception?

```
Caused by: java.lang.NullPointerException
	at java.awt.color.ICC_Profile.intFromBigEndian(ICC_Profile.java:1782)
	at java.awt.color.ICC_Profile.getNumComponents(ICC_Profile.java:1474)
	at sun.java2d.cmm.lcms.LCMSTransform.<init>(LCMSTransform.java:98)
	at sun.java2d.cmm.lcms.LCMS.createTransform(LCMS.java:173)
	at java.awt.color.ICC_ColorSpace.toRGB(ICC_ColorSpace.java:178)
	at org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB.init(PDDeviceRGB.java:68)
	at org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB.toRGBImage(PDDeviceRGB.java:108)
	at org.apache.pdfbox.pdmodel.PDDocument.<clinit>(PDDocument.java:108)
```

PdfComparator.compare() was called.

**Comment by SoltauFintel** [comment]
Just calling `new PDDocument();` in main() solves this problem.

**Comment by finsterwalder** [comment]
No idea. So did I understand your second comment correctly, that you fixed the problem?
Then I can close this ticket?

**Comment by SoltauFintel** [comment]
I will research this a little further, report here and then close the ticket. Other users could also encounter this error. Funnily enough, my JUnit test worked, but it didn't work in the productive Swing app. Could you please write something about my other ticket.

**Comment by SoltauFintel** [comment]
Update to pdfbox & fontbox 2.0.21 does not help.

**Comment by SoltauFintel** [comment]
I haven't found a better solution than calling new PDDocument() at the beginning of main().
